# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20160530_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_data',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
