# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-04 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='stock_index_data',
            new_name='index_data',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='stock_index_name',
            new_name='index_name',
        ),
    ]
